stages:
  # 建立 rancher_pipeline 專用的 Docker Image
  - name: Publish apache service image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        #pushRemote: true
        #registry: reg.406.csie.nuu.edu.tw
      env:
        PLUGIN_BUILD_ARGS: --progress=tty --network=host
        PLUGIN_DEBUG: "true"
        PLUGIN_MIRROR: https://mirror.gcr.io
        
  ## 部屬 憑證issuer (測試版本)
  #- name: deploy-apache-issuer
  #  steps:
  #  - applyYamlConfig:
  #      path: ./k8s-yaml/apache-issuer-staging.yaml

  ## 部屬 憑證issuer (正式版本)
  - name: deploy-apache-issuer
    steps:
    - applyYamlConfig:
        path: ./k8s-yaml/apache-issuer-production.yaml

  ## 部屬 apache web
  - name: deploy-apache
    steps:
    - applyYamlConfig:
        path: ./k8s-yaml/apache-deployment.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/apache-service.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/apache-ingress.yaml
